[build]
  command = "npm run build"
  publish = "dist"

[site]
  id = "4b7abf18-9a45-4228-82fa-562071c4624e"
  name = "fabulous-torte-1b63ed"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200